version: '3'
services:
  app:
    build:
      context: ./anthropic-webui
      dockerfile: Dockerfile
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    volumes:
      - ./OpenWebUIdata:/app/backend/data
volumes:
  open-webui: